create menu screen + change logic of walletaddress button with share …
samhv/aave-mobile-aap pull request #32
Opened 2022-11-15 18:16 UTC by oasm1982

![step 1](https://user-images.githubusercontent.com/93625950/201995346-eee536bc-fbac-4e05-a2e5-a0457ade7e68.jpeg)
![step 2](https://user-images.githubusercontent.com/93625950/201995367-33e7b9d3-9d0b-43af-8b83-06f2c1a0e9e4.jpeg)
![step 3](https://user-images.githubusercontent.com/93625950/201995377-0222fc47-668d-406e-bd55-88e5879b1766.jpeg)

2022-11-16 00:30 UTC, oasm1982 commented
![step 4](https://user-images.githubusercontent.com/93625950/202053735-ceafc980-3dad-4b41-8b51-bf602b897022.jpeg)

2022-11-24 00:05 UTC, oasm1982 commented
![WhatsApp Image 2022-11-23 at 16 02 29](https://user-images.githubusercontent.com/93625950/203666268-38c0b8f9-5e75-491b-b36c-d88b2af51bb0.jpeg)
![WhatsApp Image 2022-11-23 at 16 02 32](https://user-images.githubusercontent.com/93625950/203666278-9db9d48a-ecb5-4e8d-aa0f-75068fa3aba7.jpeg)

2022-11-24 00:13 UTC, samhv requested changes
couple small comments
Please remove `assets/.DS_Store`

2022-11-24 00:13 UTC, samhv commented on components/atoms/TokenIcon.tsx
>      chainId: number
given you removed it from the component's props, let's remove it from the interface

2022-11-24 00:13 UTC, samhv commented on components/screens/MenuScreen.tsx
> +export const SignedoutButton = () => {
typo -- `SignedOutButton`

2022-11-24 00:52 UTC, samhv approved these changes
lgtm

2022-11-24 00:52 UTC, merged