logic to user balance on Portfolioscreen
samhv/aave-mobile-aap pull request #7
Opened 2022-03-22 18:27 UTC by oasm1982

![IMG_04F995C4FA4B-1](https://user-images.githubusercontent.com/93625950/159550064-3431c4f6-2b88-4f49-8efe-3aff1b73ee3e.jpeg)

in this feature let's do it a logic a user balance, in white color add de integer balance and after doit (decimal balance) is the transparent white color.

2022-03-22 22:28 UTC, LuisB0605 approved these changes
lgtm

2022-03-24 10:06 UTC, samhv requested changes
couple comments, but lgtm overall

2022-03-24 10:06 UTC, samhv commented on components/molecules/UserBalance.tsx
> +        color: "#fff",
I don't think it's necessary, because you are using `StandardText`, so it's white by default

2022-03-24 10:06 UTC, samhv commented on components/molecules/UserBalance.tsx
> +			</StandardText>
Can we try using `SecondaryText` here? so, later, we don't need to use `opacity` or `color` at all

2022-03-24 10:06 UTC, samhv commented on components/molecules/UserBalance.tsx
> +        opacity: 0.4,
If we can use `SecondaryText` for it, then we don't longer need `opacity` and `color` any more

2022-03-24 19:19 UTC, samhv approved these changes
lgtm

2022-03-24 19:20 UTC, merged